# Generated by Django 4.2.7 on 2023-11-11 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='строка в сетке')),
                ('column', models.PositiveIntegerField(verbose_name='столбец в сетке')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокированный блок?')),
                ('towers_blocked', models.BooleanField(default=False, verbose_name='Занят вышкой?')),
                ('covered_with_a_tower', models.BooleanField(default=False, verbose_name='покрыт вышкой?')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='BlockTowerCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_grid.block')),
            ],
        ),
        migrations.CreateModel(
            name='CityGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение не может быть меньше 1')], verbose_name='кол-во строк в сетке')),
                ('columns', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение не может быть меньше 1')], verbose_name='кол-во столбцов в сетке')),
                ('coverage_threshold', models.PositiveIntegerField(default=30, help_text='\n        Пожалуйста укажите максимальный процент загороженности вашей сетки\n        ', verbose_name='Максимальный % покрытия')),
            ],
            options={
                'verbose_name': 'Городская сетка',
                'verbose_name_plural': 'Городские сетки',
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.PositiveIntegerField(help_text='Пожалуйста укажите какой радиус охватывает эта вышка', verbose_name='Радиус вышки')),
            ],
            options={
                'verbose_name': 'Вышка',
                'verbose_name_plural': 'Вышки',
            },
        ),
        migrations.CreateModel(
            name='TowerCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_for_tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_for_tower', to='city_grid.block', verbose_name='Выберите блок для установки вышки')),
                ('city_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_grid.citygrid')),
                ('covered_blocks', models.ManyToManyField(blank=True, through='city_grid.BlockTowerCoverage', to='city_grid.block')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_grid.tower', verbose_name='Выберите вышку')),
            ],
            options={
                'verbose_name': 'Размещение вышки',
                'verbose_name_plural': 'Размещение вышек',
            },
        ),
        migrations.AddField(
            model_name='blocktowercoverage',
            name='towercoverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_grid.towercoverage'),
        ),
        migrations.AddField(
            model_name='block',
            name='city_grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='city_grid.citygrid'),
        ),
    ]
