# Generated by Django 4.2.7 on 2023-11-12 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towercoverage',
            name='block_for_tower',
            field=models.ForeignKey(help_text='\n        Пожалуйста выберите блок для установки вышки из списка свободных блоков\n        ', on_delete=django.db.models.deletion.CASCADE, related_name='block_for_tower', to='city_grid.block', verbose_name='Выберите блок для установки вышки'),
        ),
    ]
