# Generated by Django 4.2.7 on 2023-11-11 05:28

from django.db import migrations
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='figure',
            field=django_matplotlib.fields.MatplotlibFigureField(),
        ),
    ]
