# Generated by Django 4.2.7 on 2023-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_grid', '0002_alter_blockedblock_options_alter_citygrid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citygrid',
            options={'verbose_name': 'Городская сетка', 'verbose_name_plural': 'Городские сетки'},
        ),
    ]
