# Generated by Django 4.2.7 on 2023-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_grid', '0003_alter_citygrid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citygrid',
            name='coverage_threshold',
            field=models.PositiveIntegerField(default=30, verbose_name='Минимальный % покрытия'),
        ),
    ]
